import googleapiclient.discovery


class YoutubeAPI:
    def __init__(self, api_key):
        self.api_key = api_key
        self.youtube = googleapiclient.discovery.build(
            'youtube', 'v3', developerKey=api_key)

    def get_playlist_items(self, playlist_id):
        items = []
        next_page_token = None

        while True:
            response = self.youtube.playlistItems().list(
                part="snippet",
                maxResults=50,
                playlistId=playlist_id,
                pageToken=next_page_token
            ).execute()

            for item in response['items']:
                video_id = item['snippet']['resourceId']['videoId']
                title = item['snippet']['title']
                description = item['snippet']['description']
                thumbnail_url = item['snippet']['thumbnails'].get(
                    'high', {}).get('url', None)
                if "Auto-generated by YouTube." in description:
                    aux_type = 'song'
                else:
                    aux_type = 'video'
                items.append({
                    'video_id': video_id,
                    'title': title,
                    'description': description,
                    'thumbnail_url': thumbnail_url,
                    'type': aux_type
                })

            next_page_token = response.get('nextPageToken')

            if not next_page_token:
                break

        return items
