playlistIdForMusic = 'PL_8z4vyyerkO0OsXupspGzzw3-XSjC-01'
playlistUrlForMusic = f'https://www.youtube.com/playlist?list={playlistIdForMusic}'
playlistUrlForVideo = 'PL_8z4vyyerkMhM-RSZkTpq0zELxXTVyzq'
pathForMusic = 'data/mp3/'
pathForVideo = 'data/mp4'
